# Generated by Django 5.1.1 on 2025-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthxpfront', '0003_achievement_activitylog_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('silver', 'Silver Membership'), ('gold', 'Gold Membership'), ('platinum', 'Platinum Membership'), ('coop_silver', 'Co-operate Silver Package'), ('coop_gold', 'Co-operate Gold Package'), ('coop_platinum', 'Co-operate Platinum Package')], default='silver', max_length=20),
        ),
    ]
