# Generated by Django 5.1.1 on 2025-04-01 14:52

from django.db import migrations


def clear_subscription_data(apps, schema_editor):
    Subscription = apps.get_model('healthxpfront', 'Subscription')
    Subscription.objects.all().delete()


def reverse_clear_subscription_data(apps, schema_editor):
    pass  # We can't restore deleted data


class Migration(migrations.Migration):

    dependencies = [
        ('healthxpfront', '0009_create_subscription_types'),
    ]

    operations = [
        migrations.RunPython(clear_subscription_data,
                             reverse_clear_subscription_data),
    ]
